In [1]:

from faker import Faker
import pandas as pd
fake = Faker()

In [2]:
lista = []

In [3]:
for i in range(0,10000):
    lista.append({'nombre': fake.name(), 'apellido': fake.last_name(), 'email': fake.email(), 'direccion': fake.address()})

In [4]:
#print(lista)

In [5]:
data = pd.DataFrame(lista)

In [6]:
data

,nombre,apellido,email,direccion
0,Lisa Rose,Peterson,jasminemiller@example.net,"07789 Bentley Trafficway\nWalkerhaven, TN 15191"
1,Rebecca Obrien,Jacobs,aaron68@example.net,"72323 Gilmore Lane Suite 614\nSouth Beth, ID 4..."
2,Amber Lloyd,Johnson,keithphillips@example.com,USNS Richardson\nFPO AP 80867
3,David Mendez,Hudson,cleblanc@example.org,710 Brittany Camp Suite 054\nNorth Courtneysta...
4,Mikayla Nelson,Rivera,ashley04@example.net,"723 Duncan Drive Suite 664\nJacobborough, AZ 8..."
...,...,...,...,...
9995,Nathan Green,Hernandez,luke14@example.com,397 Michael Light Suite 507\nSouth Tiffanyhave...
9996,Anthony Jones,Monroe,danielle20@example.com,"7761 Sherri Isle\nSouth Robert, TX 01588"
9997,Travis Henry,Brooks,zamorajulie@example.net,"3262 Jordan Parkways Suite 374\nWilliamfurt, M..."
9998,Theresa Owen,Willis,brittany14@example.com,"70128 Christopher Forge\nMannview, SC 77764"
9999,Francisco Gonzalez,David,cainkim@example.org,"13823 Wood Shore\nNew Raymondton, ID 07349"

In [7]:
import random

In [8]:
def age(params):
    ages = ("30", "40")
    return random.choice(ages)

In [9]:
def province(params):
    provinces = ('Loja', 'Pichincha', 'Guayas', 'Azuay', 'Manabí')
    return random.choice(provinces)

In [10]:
data['age'] = data['nombre'].apply(age)
data['province'] = data['nombre'].apply(province)

In [11]:
data

,nombre,apellido,email,direccion,age,province
0,Lisa Rose,Peterson,jasminemiller@example.net,"07789 Bentley Trafficway\nWalkerhaven, TN 15191",30,Guayas
1,Rebecca Obrien,Jacobs,aaron68@example.net,"72323 Gilmore Lane Suite 614\nSouth Beth, ID 4...",30,Pichincha
2,Amber Lloyd,Johnson,keithphillips@example.com,USNS Richardson\nFPO AP 80867,30,Guayas
3,David Mendez,Hudson,cleblanc@example.org,710 Brittany Camp Suite 054\nNorth Courtneysta...,30,Loja
4,Mikayla Nelson,Rivera,ashley04@example.net,"723 Duncan Drive Suite 664\nJacobborough, AZ 8...",40,Manabí
...,...,...,...,...,...,...
9995,Nathan Green,Hernandez,luke14@example.com,397 Michael Light Suite 507\nSouth Tiffanyhave...,30,Manabí
9996,Anthony Jones,Monroe,danielle20@example.com,"7761 Sherri Isle\nSouth Robert, TX 01588",40,Pichincha
9997,Travis Henry,Brooks,zamorajulie@example.net,"3262 Jordan Parkways Suite 374\nWilliamfurt, M...",40,Loja
9998,Theresa Owen,Willis,brittany14@example.com,"70128 Christopher Forge\nMannview, SC 77764",40,Guayas
9999,Francisco Gonzalez,David,cainkim@example.org,"13823 Wood Shore\nNew Raymondton, ID 07349",40,Guayas

In [15]:
data.to_csv('Data/mdata.csv', index=False)